### ISSUE TITLE
All in french

### ISSUE THREAD

**Issue by Zayceur** [mfron/Pokemon-Go-Bot#10]
Hi I translated all the interface to french of the source project.
Tell me if you want I help you.
https://github.com/Zayceur/Pokemon-Go-Rocket-API-MULTILANG

**Comment by mfron** [comment]
Merci ! Je prends de l aide volontier ! Tu fais de l ui ?

**Comment by Zayceur** [comment]
Un peu ouais

**Comment by Zayceur** [comment]
T'as Skype ou qqch d'autre où on peut se parler ?

**Comment by mfron** [comment]
Ouais carrement

**Comment by mfron** [comment]
Facebook directement ? Matthieu fron

**Comment by Zayceur** [comment]
Na j'ai pas FaceBook

**Comment by mfron** [comment]
lets go pr skype, slash-king

**Comment by Zayceur** [comment]
Envoyé
