### ISSUE TITLE
the bot does not transfer automatically?

### ISSUE THREAD

**Issue by Moya2k13** [mfron/Pokemon-Go-Bot#11]
I have these transfer options 
![0b8c9a1704e8b9a44a5ce2475be3b396](https://cloud.githubusercontent.com/assets/4446281/17272796/50d773b2-56a0-11e6-84cb-67afbc3ad5af.png)

but does not transfer anything :/

**Comment by Bagnous** [comment]
it does, but after 230 pokemon, you can see it on the main class, i changed it for 200, also put there is the class about envolve and transfer, change the list as you like, trust me the xp is phenomenal when he envolves then transfer loooool

**Comment by Moya2k13** [comment]
but it evolves all? and leaves Pokemons With IV greater than 80%? I do not want some Pokemons evolve, there is an option to not evolve?

**Comment by Bagnous** [comment]
no, there is the list in the EnvolveAndtransfertSeting.cs to choose which pokemon you want to envolve(rattata and others , but you can still edit it) the list is called toEnvolve, you can remove pikachu or machop or abra for exemple, only pokemon on that list will get envolved and then depending on your IV they will be transfered later or not( the transfert comes after the envolving)

**Comment by Moya2k13** [comment]
Ok! alright :D
