### ISSUE TITLE
No pokeball, pokemon got away

### ISSUE THREAD

**Issue by Lihouf** [mfron/Pokemon-Go-Bot#12]
I cant have pokeman because i run out of pokéball but pokestop doesn't give it
EDIT: Bag is full just to delete sometimes potion and revives

**Comment by mfron** [comment]
Edit the app.config on window folder

**Comment by mfron** [comment]
Ho wait. Maybe not implemented. On thé code you can search for maxpokeball value ( i writed it to 0 :#)

**Comment by Lihouf** [comment]
I 've just see that

**Comment by mfron** [comment]
Perfect
