### ISSUE TITLE
[Suggestion] Do not await Transfer

### ISSUE THREAD

**Issue by evoamac** [mfron/Pokemon-Go-Bot#15]
I'm thinking to take the await off the Transfer method. that way it just runs at the back ground making out bound call. and we can keep farming

**Comment by mfron** [comment]
Humm dont know ... Try and tell me

**Comment by evoamac** [comment]
did it, running good so far. still farming while transfering
![untitled](https://cloud.githubusercontent.com/assets/5290339/17273131/9556321a-5670-11e6-8593-566d7c8e273d.png)

**Comment by mfron** [comment]
Okay and for evolve?
