### ISSUE TITLE
New Function maybe ? [Suggestion]

### ISSUE THREAD

**Issue by Kijryz** [mfron/Pokemon-Go-Bot#16]
How about an Option just for Sniping Good Pokemons?

As Example i got an Website called : Pokesnipers.com - i find the pokemon X with the coordiantes Y,Z - so i can input the Coordinates Use Forceban on the Next Pokestop then Catch the Pokemon 
 btw: sry 4 bad english

**Comment by mfron** [comment]
Nice idea but dont kno if i have a time

**Comment by mfron** [comment]
If i got 1h i add this
