### ISSUE TITLE
Doesn't catch?

### ISSUE THREAD

**Issue by imnaeng** [mfron/Pokemon-Go-Bot#18]
The bot doesn't catch as much.. just pokestops? Other than that its just unlock catchs..

**Comment by freezea** [comment]
i have a lot of this unlock, but about 200 poke + on hour

**Comment by imnaeng** [comment]
So do I have to find out for a place with less pokestops?

**Comment by freezea** [comment]
Go to Tokyo

**Comment by freezea** [comment]
I had exactly like you in san francissco, but after change to tokyo 80k exp GREAt

**Comment by mfron** [comment]
No, get a place with most of pokestop is the best.
