### ISSUE TITLE
Is the Transfer Type IV working wrong?

### ISSUE THREAD

**Issue by Kijryz** [mfron/Pokemon-Go-Bot#19]
I dunno if its really wrong but it said for me : it transferred all my 90+ IV Pokemons.. So if i set the Option to : IV then to 90 ... will it transfer all pokemons Below ?

**Comment by Moya2k13** [comment]
I happened the same, uncomment this line 708 (if (Perfect(pokemon) >= keepPerfectPokemonLimit) continue;) in the method TransferAllGivenPokemons in MainForm.cs

**Comment by mfron** [comment]
FUCK MYSELF ! Sorry its that ->

 var unwantedPokemons = pokemons.Where(p => p.PokemonId == unwantedPokemonType && Perfect(p) > iv)
                    .OrderByDescending(p => Perfect(p)).ThenBy(p => p.Cp).ToList();

It transfert all pokemon with more than IV parameter !!! Perfect(p) > iv --- Perfect(p) < iv

**Comment by Kijryz** [comment]
so i just need to change the > where is it exactly ?

**Comment by mfron** [comment]
patch is pushed, im sorry :#
thx for this bug

**Comment by Moya2k13** [comment]
works well uncommented the line i said

**Comment by Kijryz** [comment]
Okii , thank u sir too :]

**Comment by Kijryz** [comment]
@mfron how can i see that u updated the Bot ? Cuz the last change it says its 3 Hrs away :D

**Comment by mfron** [comment]
Hololo, im so stupid, i pushed but forget my credentials, its patched now !

**Comment by Kijryz** [comment]
hehe , okay nice one thank you :)
