### ISSUE TITLE
Wait for Unlock catches

### ISSUE THREAD

**Issue by starktony1** [mfron/Pokemon-Go-Bot#22]
Im getting this a lot , can anyone tell me what is this . How to stop this from happening

**Comment by Kijryz** [comment]
I think that what the bot does, when ur at that moment softbanned so theres nothing u can do against it :P

**Comment by Zayceur** [comment]
You can press the Force unban button.

**Comment by starktony1** [comment]
ok so i reduced travel speed now Waiting for unlock catches is less in no. But still not 100% gone . Im not banned . I rechecked via force unbann

**Comment by starktony1** [comment]
![image](https://cloud.githubusercontent.com/assets/20708547/17273523/df32f47c-56d4-11e6-83fa-f7b9f7c4c7b0.png)

**Comment by Kijryz** [comment]
@starktony1 i think it is...a buffer so they dont notice ur botting .. so no perma ban (if they decide too:))

**Comment by mfron** [comment]
Its okay, you just must wait because the bot walked to faster.
