### ISSUE TITLE
Catch Pokemon from lured Pokestop

### ISSUE THREAD

**Issue by Solrian** [mfron/Pokemon-Go-Bot#3]
working on it

**Comment by mfron** [comment]
Nice thx i will add this now

**Comment by mfron** [comment]
it cant work bro ... here you get the pokemonid
var luredpokemon = pokestop.LureInfo.ActivePokemonId;

after you get un array with the only pokemon with this pokemonid :

var pokemons2 = inventory2.InventoryDelta.InventoryItems
.Select(i => i.InventoryItemData?.Pokemon)
.Where(p => p != null && p?.PokemonId == luredpokemon)
.ToArray();

and after ... you do nothing with it ...
