### ISSUE TITLE
i need help....

### ISSUE THREAD

**Issue by ponyjoseph** [mfron/Pokemon-Go-Bot#30]
it always got this messenge 
wait for unlock catchs...
than i relogin my phone to check .. it isnot   for ban 

can someone thesame ?
and  i have set CP Threshold it seem's do not work ....

**Comment by Bagnous** [comment]
The wait for unlock catch tell you, you cant catch pokemon now, it's not a bug

**Comment by ponyjoseph** [comment]
So this message is normal?

Then why it isn't drop the pokebaby? When I set cp 600.....

Thank your help info

**Comment by Bagnous** [comment]
yes the message is normal, and it will transfert the pokemon after you have 230, then it will transfer it all, i advise you to check the list of envolving pokemon also, edit it as you like and activate it, you will have more xp (500 xp by pokemon)

**Comment by ponyjoseph** [comment]
Thank you~
But I do not know why the cp3xx I got away........still can't catch poke.....

**Comment by ponyjoseph** [comment]
Sorry when did I use force unban? Is start game?

**Comment by freezea** [comment]
before first pokestop

**Comment by ponyjoseph** [comment]
Thank you freezea and guys~

**Comment by ponyjoseph** [comment]
I do not know why....when I go bot in some minutes....it will be change restating......

**Comment by ponyjoseph** [comment]
When I use force unban it will be crash relogin gmail
