### ISSUE TITLE
NEW V3 is coming soon

### ISSUE THREAD

**Issue by mfron** [mfron/Pokemon-Go-Bot#31]
Hello all, V3 is coming soon, tell me if you find a bug.

( we are looking for help, if someone want participate to the project )

**Comment by mfron** [comment]
catch is not a bug, my bot is 4 or 5 time faster than every others bot. The wait for unlock catch tell you, you cant catch pokemon now, he cannot be faster than he already is ( for the moment, with the V3 he is a little bit faster )

**Comment by starktony1** [comment]
@mfron just remove it then(at least displaying it) , seems like a bug to everyone .

**Comment by evoamac** [comment]
@mfron are we having problem for the unban functionality? 
var pokeStops = mapObjects.MapCells.SelectMany(i => i.Forts).Where(i => i.Type == FortType.Checkpoint && i.CooldownCompleteTimestampMs < DateTime.UtcNow.ToUnixTime()); yells no result when i debug it

**Comment by evoamac** [comment]
added a 10 seconds delay, solved the not getting respond problem

**Comment by zeyuss** [comment]
updated?

**Comment by supersupereight** [comment]
Hello,
I want to know the all potions are dropped issue has fixed in new version?
I met the issue even thought the MaxItemSuperPotion value has set in V1.81

**Comment by v7nce** [comment]
Bot stops every 2 hours. I'd rather use the other one for now until you can fix this issue, I have a job I need to AFK 7h a day I can't afford a bot that crashes every 2h.

**Comment by freezea** [comment]
my bot was working all night good @v7nce

**Comment by v7nce** [comment]
Now it's not even catching any pokémon :/
Don't know what's happening with this version, the other one works fine.

**Comment by mfron** [comment]
My bot is working since 24h, so i dont understand what you say

**Comment by Kijryz** [comment]
My bot diddnt worked after 5 hrs i assume its my Anti Virus but i dunno , after a clean restart i works fine again :)

**Comment by Grunkhead** [comment]
Looking for a stable build with IV transfer which does not stop after 2 hours of botting, my bot stops at the moment after each 2 hours which is very annoying.

**Comment by mfron** [comment]
V3 aivable :)

**Comment by zeyuss** [comment]
@mfron I don't see the .exe file?
