### ISSUE TITLE
pokestops

### ISSUE THREAD

**Issue by freezea** [mfron/Pokemon-Go-Bot#32]
Hi, bot works very well , can you do in next uptade bot a little longer stayed with Pokemon , because 90% in my bot is pokestop and 10% pokemons  :D

**Comment by Zayceur** [comment]
The Bot, at this moment, just visits pokestop and if there's any pokemon, it will try to catch them.

**Comment by freezea** [comment]
nevermind, it was my fault 600km/h in settings xDDD
