### ISSUE TITLE
Wait for unlock catchs ...

### ISSUE THREAD

**Issue by Grunkhead** [mfron/Pokemon-Go-Bot#33]
When starting the bot it does not do anything more then saying about 5 times 'Wait for unlock catchs ...' most of the time while I am unbanned.
![image](https://cloud.githubusercontent.com/assets/746279/17276378/00a0d93c-5728-11e6-95af-ec713eeb2636.png)
Sometimes, when I immediately use force ban after the purple level text appears it works after he succeeds unbanning me. Sometimes it stops working again after saying 'Start force unban ...'.

How is this possible?

**Comment by mfron** [comment]
Stop unlock catchs, is when the client is to faster for the server, he must wait for catch pokemons. (Or sometimes, when you are softbanned (use unban) or when you already taked it (rarely and patched in the V3))

**Comment by freezea** [comment]
when v3? :D

**Comment by Grunkhead** [comment]
Ah, thanks for explaining this. :+1:
