### ISSUE TITLE
V3 is now aivable ! 

### ISSUE THREAD

**Issue by mfron** [mfron/Pokemon-Go-Bot#35]
Hello all ! Enjoy the new V3!
 
I worked on the V3, definitively the fastest Pokemon GO BOT.
Got alot of functionnality but need a UI for manage it.
Someone can help me for dev the UI ?

Report me if you find a bug :)

**Comment by freezea** [comment]
WORKS PERFECT!!! THANKS BRO, IN SAN FRANCISSCO 120K EXP ;D

**Comment by mfron** [comment]
GO on tokyo center, launch it and enjoy. ;)

**Comment by freezea** [comment]
I was but i have there smaller than san francissco

**Comment by freezea** [comment]
but i can try

**Comment by freezea** [comment]
u mean this?  
![bez tytulu](https://cloud.githubusercontent.com/assets/20640540/17276884/c5c99296-5735-11e6-8234-2c3a171ac312.png)

**Comment by mfron** [comment]
![image](https://cloud.githubusercontent.com/assets/11887274/17276894/fc0acd98-5735-11e6-988e-95ac9f7090ba.png)

**Comment by mfron** [comment]
oups

**Comment by freezea** [comment]
xD wait

**Comment by mfron** [comment]
I will change my pw now ^^

**Comment by freezea** [comment]
how can i change lantitude without pointing? i dont know here it is xD

**Comment by Bagnous** [comment]
am i the only one that , when i change to ptc login it stays want to log with google??even in the app.config i changed it manually, and still, of course on the setting it's Ptc also

**Comment by mfron** [comment]
![image](https://cloud.githubusercontent.com/assets/11887274/17276914/6e352c56-5736-11e6-88cc-c0368f85a6cb.png)

**Comment by mfron** [comment]
For a bug report, create a topic, i will solve them fast

**Comment by freezea** [comment]
Thanks bro <3

**Comment by kaster44** [comment]
hi. I do not have visual studio. Can you give me the link of the latest built release ? Thank you so much :)

**Comment by freezea** [comment]
san francissco still the best for me :D

**Comment by jiemojiemo** [comment]
Thanks! It is very helpful !
