### ISSUE TITLE
Bug detected in V3 at startup

### ISSUE THREAD

**Issue by Grunkhead** [mfron/Pokemon-Go-Bot#37]
![image](https://cloud.githubusercontent.com/assets/746279/17276900/20e391e0-5736-11e6-844d-8acffdfdabb1.png)

**Comment by Grunkhead** [comment]
Seems to work good after restart somehow.

**Comment by mfron** [comment]
You cannot go where 0 pokestops are aivable

**Comment by Grunkhead** [comment]
This is in Central Park New York.

![image](https://cloud.githubusercontent.com/assets/746279/17276925/a8346f0c-5736-11e6-9ab1-177180942041.png)

Doesn't do anything here, evolving is set OFF. Do I have to wait?

**Comment by Grunkhead** [comment]
That was in Central Park New York, it seems to work now.

**Comment by chj2mina** [comment]
Run +100000 exp per hour i run 20p not cash very good thanks

**Comment by supersupereight** [comment]
Hello mfron,
I want to use IV mode, in specific pokemons that I wnat to keep all(i,e don't trans.) , other pokemons are not in the list that follow the rule of mode.

How do I achieve this purpose?
