### ISSUE TITLE
[Envolv]No more envolving befaure transfering??

### ISSUE THREAD

**Issue by Bagnous** [mfron/Pokemon-Go-Bot#39]
Hi all,
Now the bot doesn't envolve the pokemons from the list before it transfers them, 
Do you know why?

**Comment by mfron** [comment]
For question of optimisation, 0 pokemons will try to be  evolved if you dont have a least 50 candy

**Comment by Bagnous** [comment]
OMG i just checked..., i feeeel soooo stupid looooooool, i spent all the candys already 
sorrryyyy for the bothering
