### ISSUE TITLE
Error PokemonInventoryFull

### ISSUE THREAD

**Issue by jiemojiemo** [mfron/Pokemon-Go-Bot#41]
Why？I set IV duplicate mode, and after this error hanpped, the bot will alway wait unlock catching.
It seems never transfer Pokemon

**Comment by mfron** [comment]
For question of optimisation, pokemons will be evolved/transfered if you got more than 230 pkms

**Comment by jiemojiemo** [comment]
I know that, but it did not evolved/transfered even if I got 241 pkms.

**Comment by jiemojiemo** [comment]
Ok, It just evolved, no transferd

**Comment by jiemojiemo** [comment]
![1](https://cloud.githubusercontent.com/assets/13779459/17277387/2e967f26-5774-11e6-833f-6fb28b58c930.PNG)
![2](https://cloud.githubusercontent.com/assets/13779459/17277388/31304e2e-5774-11e6-8390-5c467e2b92e7.PNG)
Look picture for details

**Comment by jiemojiemo** [comment]
oh no!this error hanppe again, anyone help?

**Comment by jiemojiemo** [comment]
MY BAD!I am really sorry. I modify the transfer list in a wrong way. 
It is work after I corrected it!
THANK YOU  BUDDY!
