### ISSUE TITLE
trasfer pokemon

### ISSUE THREAD

**Issue by relapz3** [mfron/Pokemon-Go-Bot#43]
It seems V3 would not transfer pokemon, cp threshold was set to 200, yet they stays in inventory. BTW excellent work man. Very organized coding.

**Comment by Zayceur** [comment]
I think the pokemon are transferred when there's more than 230 in your inventory. 
I need to confirm that.

**Comment by Zayceur** [comment]
See issue #42

**Comment by relapz3** [comment]
Sorry, I did not see that. I am going to confirm.

**Comment by jag0903** [comment]
why does the IV duplicates not working?

**Comment by user8285** [comment]
@ relapz3 over 230 pokemon. I know get pokemon inventory error. I have to manually transfer.
