### ISSUE TITLE
lol transfer

### ISSUE THREAD

**Issue by freezea** [mfron/Pokemon-Go-Bot#45]
[15:10:14 ] Pokemon Kingler with 1136 CP and IV at 51,11111% is transfered

i have option duplicate and this every catch any pokemon wtf?

**Comment by Zayceur** [comment]
Do you have only duplicate or duplicate IV?

**Comment by freezea** [comment]
only duplicate, im downloading again bot and let see

**Comment by Zayceur** [comment]
Ok

**Comment by freezea** [comment]
problem probably solved, but now i have so much less pokemons>pokestops, or its maybe just location,  what is the best location for boting? :D  i m in san francissco

**Comment by freezea** [comment]
hahha nvm, problem again solved xD
