### ISSUE TITLE
Bot stops again after about 2 hours of runtime

### ISSUE THREAD

**Issue by Grunkhead** [mfron/Pokemon-Go-Bot#47]

**Comment by Zayceur** [comment]
See issue #42

**Comment by Zayceur** [comment]
See issue #20

**Comment by Grunkhead** [comment]
I did, my connection is fine. Seems like the bot stops after finishing al the pokestops.

**Comment by Grunkhead** [comment]
After 1 hour and 30 minutes it stopped working again.
![image](https://cloud.githubusercontent.com/assets/746279/17278353/dc9670fe-575b-11e6-8224-d3d622f0bbd6.png)
![image](https://cloud.githubusercontent.com/assets/746279/17278355/e87b8760-575b-11e6-860a-e1ae34a2fc17.png)

**Comment by mfron** [comment]
not bad, 203 pkms/h ^^

Hummm .... i think i know why will be fixed

**Comment by Grunkhead** [comment]
@mfron hope you will do a minor fix, so I could test it tonight. ^^

**Comment by hyunkim40** [comment]
has to issue been fixed?? :P
