### ISSUE TITLE
Force Unban 

### ISSUE THREAD

**Issue by Kijryz** [mfron/Pokemon-Go-Bot#48]
Imo Force unban should have Prioritoy against wait for unlock catching - i just switched to Japan and the bot wont do anything until im no longer Banned... It just says: Starting force unban nothing more..

**Comment by freezea** [comment]
i have this same, im doing force ban on another bot from squirtle and than bot here xD

**Comment by mfron** [comment]
its patched

**Comment by mfron** [comment]
tell me if it not work again

**Comment by freezea** [comment]
@mfron now finally its working

**Comment by kaster44** [comment]
@freezea can you upload the latest build exe version to somewhere ? I do not have visual studio

**Comment by Zayceur** [comment]
@kaster44 I'll upload it in the release section. Please wait

**Comment by kaster44** [comment]
@Zayceur you are the king man
