### ISSUE TITLE
error

### ISSUE THREAD

**Issue by freezea** [mfron/Pokemon-Go-Bot#5]
![image](https://cloud.githubusercontent.com/assets/20640540/17271441/f9bf8444-567b-11e6-90a0-5b304906e62b.png)

what should i do? im trying ctrl+f5 and set as startup project

**Comment by mfron** [comment]
okay listen me are you okay ?

**Comment by freezea** [comment]
? can you just help me? i have debug folder and all of this items but didnt working

**Comment by mfron** [comment]
Hoi okay, are you rdy to listen me ?

**Comment by freezea** [comment]
Yes.

**Comment by mfron** [comment]
Okay on the right you got a list, reduce every items

**Comment by freezea** [comment]
ok, and what next?

**Comment by mfron** [comment]
screen ?

**Comment by freezea** [comment]
what u mean "reduce" delete this items from right side?

**Comment by freezea** [comment]
right click and remove?

**Comment by mfron** [comment]
, item on right side must be compiled, so generate them

**Comment by freezea** [comment]
they're,  and i have this
![image](https://cloud.githubusercontent.com/assets/20640540/17271988/109aeeec-568b-11e6-9ebb-1caccccd4c28.png)

**Comment by freezea** [comment]
bot from detective is working on this same virtual studio on VPS

**Comment by freezea** [comment]
but this no ;/

**Comment by mfron** [comment]
right click pokemongo.rocketAPI and click generate
right click on pokemongo.rocketapi.windows set at startup 

and here you can start it

**Comment by freezea** [comment]
but i dont have option "generate" 
![image](https://cloud.githubusercontent.com/assets/20640540/17272056/de6c4590-568c-11e6-83b9-a3f2818cf1f5.png)

**Comment by mfron** [comment]
build this
and the another one, set as startup project

**Comment by freezea** [comment]
Still didnt working , can you please upload your version which working and send me? i did this with doktor version with somebody and was good

**Comment by freezea** [comment]
i mean your folder but without any passwords etc ofc

**Comment by freezea** [comment]
hm? :p
