### ISSUE TITLE
Where can I control the distance traveled?

### ISSUE THREAD

**Issue by FernandezR** [mfron/Pokemon-Go-Bot#52]
The previous version had a maxDist variable that could be adjusted to keep the bot in a specific place

**Comment by mfron** [comment]
Wait, not implemented for the moment, im working on the UI, soon ^^

**Comment by mfron** [comment]
its added

Change the function call for traveling  ( movements.cs you will find 4 travelins functions ) replace the one in Execute() function on Mainform.cs
