### ISSUE TITLE
XP Count wrong

### ISSUE THREAD

**Issue by fab0nymous** [mfron/Pokemon-Go-Bot#53]
The XP Count is wrong. It shows a negative number. it counts backwards till 0 and then to the xp limit of that certain lvl.

like in that picture. it counts till 0 and after that it will count to 350.000:
![image](https://cloud.githubusercontent.com/assets/20743863/17278617/619049ec-5761-11e6-80aa-40139b4d7051.png)

**Comment by mfron** [comment]
Patched, sorry ^^
