### ISSUE TITLE
I am wondering where I can set the white list for transfering?

### ISSUE THREAD

**Issue by elffish** [mfron/Pokemon-Go-Bot#56]

**Comment by mfron** [comment]
Yes you can set whitelist for transfert in the file catchEvolveTransfertSettings.cs

**Comment by Zayceur** [comment]
Now you can use the UI !!!
See the Pokémon button.

**Comment by bl4zevenaar** [comment]
transfer pokemon not work.

**Comment by jiemojiemo** [comment]
Same problem, I remove Bulbasaur from toTransfert, But it's not work.
Because of it, I can't catch the specified pokemon

**Comment by Zayceur** [comment]
Try last version !
