### ISSUE TITLE
How to start it?

### ISSUE THREAD

**Issue by Roydeking52** [mfron/Pokemon-Go-Bot#57]
How to start and setup the bot?
Is it Windows or Linux?

**Comment by mfron** [comment]
Windows, download Visual studio community and open the project, F5 will build and run

**Comment by Roydeking52** [comment]
With file do i have to open?

**Comment by Roydeking52** [comment]
and then ? with file in the Rocket Api do i have to open?

**Comment by Roydeking52** [comment]
![knipsel](https://cloud.githubusercontent.com/assets/20264961/17279537/74092e08-5776-11e6-921b-445e97e751f5.PNG)

**Comment by Roydeking52** [comment]
I finaly find the solution.

**Comment by mfron** [comment]
ok ! perfect :) enjoy
