### ISSUE TITLE
Get a error

### ISSUE THREAD

**Issue by maestroi** [mfron/Pokemon-Go-Bot#59]
https://chuck.ovh/screenshot/v1TD5pA3a1yq.png

More info:

i have Windows 10 64x,
Visual Studio 2015 community edition.
Download and opend project and got this error,

**Comment by kingcreek** [comment]
right click on PokemonGo.Rocket API.Window on the right side of the screen inside solution explorer and click Set as StartUp Project

**Comment by maestroi** [comment]
@kingcreek works thnx :D
