### ISSUE TITLE
[PROB] Transfers and envolving

### ISSUE THREAD

**Issue by Bagnous** [mfron/Pokemon-Go-Bot#6]
Hi,first of all thx so much for this hard working bot (75k/h), but i have a little problem, the pokemons are not getting transfered, i always set duplicated mode, but now it doesn't even transfert, so i changed to IV transfer, same thing, no one getting transfered, and also, the envolve pokemon is checked, and the list of pokemons to envolve is not empty, but still no one get envolved and transfered
thx

**Comment by mfron** [comment]
Transfert is applied after 230 pkms,( optimised ;) )

**Comment by Bagnous** [comment]
ahhhh ok thx, and they get envolved at 230 also?? because none is getting envolved

**Comment by Lihouf** [comment]
Unban doesn't fix that the  pokestop, when this happen i recieve a popup on my phone says i need to reconnect because my data was change. I think it's appens because of the security option of the google account (not sure)

**Comment by Bagnous** [comment]
i'm using ptc -_-"

**Comment by Lihouf** [comment]
well maybe is not a loggin issue but i have no pokestop in the official app maybe temp ban or something like this

**Comment by bozoweed** [comment]
try to close and clear cache after relaunch the game
tips: make tp to you position with bot and make force unbann after login in app on you'r phone work 100%
