### ISSUE TITLE
i have an idea freezing

### ISSUE THREAD

**Issue by freezea** [mfron/Pokemon-Go-Bot#66]
I have an idea in , the next uptade can be done so that if the bot will without any activity by 1-2min , then reset or something

**Comment by freezea** [comment]
now i have freeze after 10min, but yesterday was fine...

**Comment by starktony1** [comment]
It should be if bot Does not do anything for more than 6 mins , then Restart . Coz 5 mins in Cooldown time of Pokestops . 

So bot doesnt mix up :)

@freezea nice idea 
@mfron  please implement this

**Comment by freezea** [comment]
ERROR ->  Cannot farm without at least 1 pokestop near you.  

What is this now? im not softbanned , 237 pokestops in my place

**Comment by freezea** [comment]
after changed place problem solved

**Comment by freezea** [comment]
1h without freeze, wow xD

**Comment by freezea** [comment]
@mfron  thanks dude
