### ISSUE TITLE
ERROR - Cannot farm without at least 1 pokestop near you.

### ISSUE THREAD

**Issue by Grunkhead** [mfron/Pokemon-Go-Bot#68]
![image](https://cloud.githubusercontent.com/assets/746279/17292836/abf9ac54-57ec-11e6-8076-4eccc9c5aae7.png)

**Comment by Zayceur** [comment]
Try another location

**Comment by Grunkhead** [comment]
Oh yeah sorry, I forgot that one. That would work indeed, thanks.
