### ISSUE TITLE
remove the result window of mass transfer

### ISSUE THREAD

**Issue by jiemojiemo** [mfron/Pokemon-Go-Bot#70]
![default](https://cloud.githubusercontent.com/assets/13779459/17296519/44e72f3a-5834-11e6-83fe-588c772af4e1.PNG)
It is redundant..

**Comment by freezea** [comment]
No, this is beatifiul.

**Comment by relapz3** [comment]
LMAO no it is not

**Comment by freezea** [comment]
i mean this 
Chinese Stamps xD

**Comment by jiemojiemo** [comment]
You always know the result, so it's redundant.
If you select 100 pokemons, and you need click 100 times. It's BAD!

**Comment by Zayceur** [comment]
That's not our application, we can't help you.

**Comment by jiemojiemo** [comment]
Ok,maybe I can do it by myself
