### ISSUE TITLE
No German Pokemon names

### ISSUE THREAD

**Issue by fab0nymous** [mfron/Pokemon-Go-Bot#8]
Hi,

thank you for your bot. its working incredibly good. in your feature list you say that there ist a german language option. but editing the config to german doesnt work. i dont see any language file oder german pokemon names in your code either. so i guess its just not implemented?

**Comment by mfron** [comment]
I will correct this now. 

Im happy if you like my bot.

**Comment by mfron** [comment]
Its patched and pushed :)

**Comment by fab0nymous** [comment]
thanks for your fast support, but sadly its not working. when the bot tries to catch a pokemon i get an error in line 409 in MainForm.cs. in this line you try to get the german names over a website

**Comment by mfron** [comment]
ho

**Comment by mfron** [comment]
sorry i will look that

**Comment by mfron** [comment]
Patched ?

**Comment by mfron** [comment]
@fab0nymous  its patched now :)

**Comment by fab0nymous** [comment]
Yes its working, thank you. Could you implement this for the PokeUI too? Would be great

and whats that with "[21:06:19 ] Wait for unlock catchs ..."?

**Comment by mfron** [comment]
Its new, its because i otpimised the client, im forced to unlock catchs before start catching pkmns
