### ISSUE TITLE
Error in transfer pokemon

### ISSUE THREAD

**Issue by FernandezR** [mfron/Pokemon-Go-Bot#9]
on line 663:

var unwantedPokemons = pokemons.Where(p => p.PokemonId == unwantedPokemonType && Perfect(p) > iv) .OrderByDescending(p => Perfect(p)).ThenBy(p => p.Cp).Skip(1).ToList(); 

Perfect(p) > iv should be Perfect(p) < iv, so that it only transfers pokemon below the iv set in config

**Comment by mfron** [comment]
Oups forget skip one

**Comment by mfron** [comment]
Patched

**Comment by FernandezR** [comment]
@mfron The skip is fine, the problem is that you are transferring every pokemon above your IV threshold when you actually want to transfer everything below the threshold.

**Comment by mfron** [comment]
XD yep, im so sorry, its patched
